spring:
  datasource:
    url: jdbc:mysql://localhost/poetry?useUnicode=true&characterEncoding=UTF8&character_set_server=UTF8MB4&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    max-active: 40
    max-idle: 16
    min-idle: 16
    initial-size: 10
  freemarker:
      template-loader-path: classpath:/web/
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl
  mvc:
    static-path-pattern: /**


mybatis:
    typeAliasesPackage: org.xin.domain
    mapperLocations: classpath:mapper/*.xml
    config-location: classpath:/mybatis-config.xml

baseweb:
  description:
    length: 128